apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/wasdqaz/devopp-lap.git
    targetRevision: HEAD
    path: helmCharts
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
