spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  server:
    port: 8081  # Cổng được thay đổi ở đây

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  server:
    port: 8081  # Cổng cũng được thay đổi ở đây nếu chạy với profile docker
