name: Build & Test with Coverage Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Give execute permission to mvnw
      run: chmod +x mvnw

    - name: Build and verify with coverage check
      run: ./mvnw clean verify
