# /charts/spring-petclinic-service/chart/values.yaml
replicas: 2

image:
  repository: 22127210/spring-petclinic-config-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888  # Change to 8888 - the default Config Server port

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  # Add Git repository configuration or other required env variables
  # - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
  #   value: "https://github.com/YOUR-ORG/YOUR-CONFIG-REPO"

livenessProbe:
  path: /actuator/health
  port: 8888

readinessProbe:
  path: /actuator/health
  port: 8888


