# /charts/spring-petclinic-service/chart/values.yaml
replicas: 2

image:
  repository: 22127210/spring-petclinic-config-server
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker

    
livenessProbe:
  path: /actuator/health
  port: 8888

readinessProbe:
  path: /actuator/health
  port: 8888

configServer:
  enabled: true
  image:
    repository: 22127210/spring-petclinic-config-server
    tag: latest
  service:
    name: config-server
    port: 8888
